/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AsideItem: typeof import('./src/components/card-manage/basic/AsideItem.vue')['default']
    BasicCard: typeof import('./src/components/card-manage/basic/BasicCard.vue')['default']
    BasicCheckbox: typeof import('./src/components/card-manage/basic/BasicCheckbox.vue')['default']
    BasicGroup: typeof import('./src/components/card-manage/basic/BasicGroup.vue')['default']
    BasicHeaderToolbar: typeof import('./src/components/card-manage/basic/BasicHeaderToolbar.vue')['default']
    BasicLayout: typeof import('./src/components/card-manage/basic/BasicLayout.vue')['default']
    BasicSearch: typeof import('./src/components/card-manage/basic/BasicSearch.vue')['default']
    BasicTag: typeof import('./src/components/card-manage/basic/BasicTag.vue')['default']
    BasicText: typeof import('./src/components/card-manage/basic/BasicText.vue')['default']
    CardManage: typeof import('./src/components/CardManage.vue')['default']
    CardToolbar: typeof import('./src/components/card-manage/basic/CardToolbar.vue')['default']
    Charts: typeof import('./src/components/card-manage/router/Charts.vue')['default']
    CommonMenu: typeof import('./src/components/card-manage/commonMenu/CommonMenu.vue')['default']
    ElAside: typeof import('element-plus/es')['ElAside']
    ElContainer: typeof import('element-plus/es')['ElContainer']
    ElHeader: typeof import('element-plus/es')['ElHeader']
    ElMain: typeof import('element-plus/es')['ElMain']
    FoldText: typeof import('./src/components/card-manage/basic/FoldText.vue')['default']
    Group: typeof import('./src/components/siyuan/siyuan/setting/Group.vue')['default']
    HiglightAside: typeof import('./src/components/card-manage/basic/HiglightAside.vue')['default']
    InboxAside: typeof import('./src/components/card-manage/basic/InboxAside.vue')['default']
    Input: typeof import('./src/components/siyuan/siyuan/setting/Input.vue')['default']
    InputCookie: typeof import('./src/components/dialog/InputCookie.vue')['default']
    Item: typeof import('./src/components/siyuan/siyuan/setting/Item.vue')['default']
    MiniItem: typeof import('./src/components/siyuan/siyuan/setting/MiniItem.vue')['default']
    NotFound: typeof import('./src/components/card-manage/router/NotFound.vue')['default']
    Panel: typeof import('./src/components/siyuan/siyuan/setting/Panel.vue')['default']
    Panels: typeof import('./src/components/siyuan/siyuan/setting/Panels.vue')['default']
    PreivewImg: typeof import('./src/components/card-manage/basic/PreivewImg.vue')['default']
    SelectedToolbar: typeof import('./src/components/card-manage/basic/SelectedToolbar.vue')['default']
    Setting: typeof import('./src/components/Setting.vue')['default']
    Svg: typeof import('./src/components/siyuan/siyuan/misc/Svg.vue')['default']
    Sync: typeof import('./src/components/dialog/Sync.vue')['default']
    Tabs: typeof import('./src/components/siyuan/siyuan/setting/Tabs.vue')['default']
    Tips: typeof import('./src/components/siyuan/siyuan/dialog/Tips.vue')['default']
    View: typeof import('./src/components/card-manage/router/View.vue')['default']
  }
}
